language: node_js

node_js:
  - "stable"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

branches:
  only:
    - master

script:
  # run unit tests
  - npm run test
  # update Protractor and Selenium including ChromeDriver
  # - npm run webdriver-update
  # launch Selenium standalone in the background
  # - npm run webdriver-start
  # run Protractor E2E tests
  # - npm run ci-e2e